INFO _internal.py:88  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:88  * Restarting with stat
WARNING _internal.py:88  * Debugger is active!
INFO _internal.py:88  * Debugger PIN: 800-420-469
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:06:50] "GET / HTTP/1.1" 500 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:06:50] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:06:50] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:06:50] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:06:50] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:06:50] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:06:51] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:88  * Detected change in '/Users/flt/Documents/zhuchen/test_dev/run.py', reloading
INFO _internal.py:88  * Restarting with stat
WARNING _internal.py:88  * Debugger is active!
INFO _internal.py:88  * Debugger PIN: 800-420-469
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:08:07] "GET / HTTP/1.1" 500 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:08:07] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:08:07] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:08:07] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:08:07] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:08:07] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:08:08] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:88  * Detected change in '/Users/flt/Documents/zhuchen/test_dev/run.py', reloading
INFO _internal.py:88  * Restarting with stat
WARNING _internal.py:88  * Debugger is active!
INFO _internal.py:88  * Debugger PIN: 800-420-469
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:08:58] "GET / HTTP/1.1" 500 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:08:58] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:08:58] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:08:58] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:08:58] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:08:58] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:08:59] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:88  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:88  * Restarting with stat
WARNING _internal.py:88  * Debugger is active!
INFO _internal.py:88  * Debugger PIN: 800-420-469
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:16:07] "GET / HTTP/1.1" 500 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:16:07] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:16:07] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:16:07] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:16:07] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:16:07] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:88  * Detected change in '/Users/flt/Documents/zhuchen/test_dev/jd_app/config.py', reloading
INFO _internal.py:88  * Restarting with stat
WARNING _internal.py:88  * Debugger is active!
INFO _internal.py:88  * Debugger PIN: 800-420-469
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:22:13] "GET / HTTP/1.1" 500 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:22:13] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:22:13] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:22:13] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:22:13] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:22:13] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:22:13] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:22:37] "GET / HTTP/1.1" 500 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:22:37] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:22:37] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:22:37] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:22:37] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:22:37] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:22:37] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:88  * Detected change in '/Users/flt/Documents/zhuchen/test_dev/jd_app/config.py', reloading
INFO _internal.py:88  * Restarting with stat
WARNING _internal.py:88  * Debugger is active!
INFO _internal.py:88  * Debugger PIN: 800-420-469
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:23:23] "GET / HTTP/1.1" 500 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:23:23] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:23:23] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:23:23] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:23:23] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:23:23] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:23:24] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:88  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:88  * Restarting with stat
WARNING _internal.py:88  * Debugger is active!
INFO _internal.py:88  * Debugger PIN: 800-420-469
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:29:11] "GET / HTTP/1.1" 500 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:29:12] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:29:12] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:29:12] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:29:12] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:29:12] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:29:13] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO _internal.py:88  * Detected change in '/Users/flt/Documents/zhuchen/test_dev/jd_app/config.py', reloading
INFO _internal.py:88  * Restarting with stat
WARNING _internal.py:88  * Debugger is active!
INFO _internal.py:88  * Debugger PIN: 800-420-469
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:32:28] "GET / HTTP/1.1" 500 -
ERROR _internal.py:88 Error on request:
Traceback (most recent call last):
  File "/Users/flt/.virtualenvs/zhuchen/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/Users/flt/.virtualenvs/zhuchen/lib/python2.7/site-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/Users/flt/.virtualenvs/zhuchen/lib/python2.7/site-packages/werkzeug/serving.py", line 227, in write
    self.send_header(key, value)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 401, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 41] Protocol wrong type for socket
INFO _internal.py:88 127.0.0.1 - - [19/Mar/2018 02:35:26] "GET / HTTP/1.1" 500 -
ERROR _internal.py:88 Error on request:
Traceback (most recent call last):
  File "/Users/flt/.virtualenvs/zhuchen/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/Users/flt/.virtualenvs/zhuchen/lib/python2.7/site-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/Users/flt/.virtualenvs/zhuchen/lib/python2.7/site-packages/werkzeug/serving.py", line 236, in write
    self.send_header('Server', self.version_string())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 401, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe
